services:
  chunk-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
      - LOG_LEVEL=info
      - LOG_LEVEL_NETWORK=warn
      - LOG_LEVEL_GAMELOOP=warn
      - LOG_LEVEL_EVENTS=warn
    restart: unless-stopped
    networks:
      - mmo_network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4096M
        reservations:
          cpus: "2"
          memory: 2048M

networks:
  mmo_network:
    external: true
