services:
  chunk-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - GAME_SERVER_HOST=game-server
    restart: unless-stopped
    networks:
      - mmo_network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4096M
        reservations:
          cpus: "2"
          memory: 2048M

networks:
  mmo_network:
    external: true
